### ISSUE TITLE
openid/indieauth.com/openid throws an error

### ISSUE THREAD

**Issue by aswathrao** [aaronpk/IndieAuth.com#169] opened 2017-08-22 16:32 UTC
demo.mypor.ch is an OpenID RP. I have an OpenID that is delegated to indieauth.com (for ex demo.mypor.ch/id/aswath). When I try to authenticate this OpenID, I get the following error: error: Query dict must have one value for each key, not lists of values. Query is {"openid.ns"=>"http://specs.openid.net/auth/2.0", "openid.claimed_id"=>"https://demo.mypor.ch/id/aswath", "openid.identity"=>"https://demo.mypor.ch/id/aswath", "openid.return_to"=>"https://demo.mypor.ch/pages/return", "openid.realm"=>"https://demo.mypor.ch/pages/return", "openid.assoc_handle"=>"{HMAC-SHA256}{598d6d0a}{wSaqsQ==}", "openid.mode"=>"checkid_setup", "captures"=>[]}

I think the root cause is b/c when i visit openid.indieauth.com/openid, I get a similar error: error: Query dict must have one value for each key, not lists of values. Query is {"captures"=>[]}. It used to work properly before. This error started to appear since last Friday or so.

**Comment by aaronpk** [comment] 2017-08-24 17:53
This was caused by a change in the Sinatra gem. Fixed in 3cf0747b0c5cb2a5dd0dea522fef839aa123319f

**Closed by aaronpk** 2017-08-24 17:53 UTC
